#if !defined __CR_ASSET_H__
#define __CR_ASSET_H__

#include "CR_common.h"

extern const char* const CR_asset_final_vert;
extern const char* const CR_asset_final_frag;

extern const char* const CR_asset_scene_vert;
extern const char* const CR_asset_scene_frag;

extern const Uint8* const CR_asset_default_png;
extern const size_t CR_asset_default_png_size;

extern const Uint8* const CR_asset_blank_png;
extern const size_t CR_asset_blank_png_size;

extern const Uint8* const CR_asset_background_1_png;
extern const size_t CR_asset_background_1_png_size;
extern const Uint8* const CR_asset_background_2_png;
extern const size_t CR_asset_background_2_png_size;
extern const Uint8* const CR_asset_background_3_png;
extern const size_t CR_asset_background_3_png_size;
extern const Uint8* const CR_asset_background_4_png;
extern const size_t CR_asset_background_4_png_size;
extern const Uint8* const CR_asset_background_5_png;
extern const size_t CR_asset_background_5_png_size;

extern const Uint8* const CR_asset_level_png;
extern const size_t CR_asset_level_png_size;

extern const Uint8* const CR_asset_tile_1_png;
extern const size_t CR_asset_tile_1_png_size;
extern const Uint8* const CR_asset_tile_2_png;
extern const size_t CR_asset_tile_2_png_size;
extern const Uint8* const CR_asset_tile_3_png;
extern const size_t CR_asset_tile_3_png_size;
extern const Uint8* const CR_asset_tile_4_png;
extern const size_t CR_asset_tile_4_png_size;
extern const Uint8* const CR_asset_tile_5_png;
extern const size_t CR_asset_tile_5_png_size;
extern const Uint8* const CR_asset_tile_6_png;
extern const size_t CR_asset_tile_6_png_size;
extern const Uint8* const CR_asset_tile_7_png;
extern const size_t CR_asset_tile_7_png_size;
extern const Uint8* const CR_asset_tile_8_png;
extern const size_t CR_asset_tile_8_png_size;
extern const Uint8* const CR_asset_tile_9_png;
extern const size_t CR_asset_tile_9_png_size;
extern const Uint8* const CR_asset_tile_10_png;
extern const size_t CR_asset_tile_10_png_size;
extern const Uint8* const CR_asset_tile_11_png;
extern const size_t CR_asset_tile_11_png_size;
extern const Uint8* const CR_asset_tile_12_png;
extern const size_t CR_asset_tile_12_png_size;
extern const Uint8* const CR_asset_tile_13_png;
extern const size_t CR_asset_tile_13_png_size;
extern const Uint8* const CR_asset_tile_14_png;
extern const size_t CR_asset_tile_14_png_size;
extern const Uint8* const CR_asset_tile_15_png;
extern const size_t CR_asset_tile_15_png_size;
extern const Uint8* const CR_asset_tile_16_png;
extern const size_t CR_asset_tile_16_png_size;
extern const Uint8* const CR_asset_tile_17_png;
extern const size_t CR_asset_tile_17_png_size;
extern const Uint8* const CR_asset_tile_18_png;
extern const size_t CR_asset_tile_18_png_size;
extern const Uint8* const CR_asset_tile_19_png;
extern const size_t CR_asset_tile_19_png_size;
extern const Uint8* const CR_asset_tile_20_png;
extern const size_t CR_asset_tile_20_png_size;
extern const Uint8* const CR_asset_tile_21_png;
extern const size_t CR_asset_tile_21_png_size;
extern const Uint8* const CR_asset_tile_22_png;
extern const size_t CR_asset_tile_22_png_size;
extern const Uint8* const CR_asset_tile_23_png;
extern const size_t CR_asset_tile_23_png_size;
extern const Uint8* const CR_asset_tile_24_png;
extern const size_t CR_asset_tile_24_png_size;
extern const Uint8* const CR_asset_tile_25_png;
extern const size_t CR_asset_tile_25_png_size;
extern const Uint8* const CR_asset_tile_26_png;
extern const size_t CR_asset_tile_26_png_size;
extern const Uint8* const CR_asset_tile_27_png;
extern const size_t CR_asset_tile_27_png_size;
extern const Uint8* const CR_asset_tile_28_png;
extern const size_t CR_asset_tile_28_png_size;
extern const Uint8* const CR_asset_tile_29_png;
extern const size_t CR_asset_tile_29_png_size;
extern const Uint8* const CR_asset_tile_30_png;
extern const size_t CR_asset_tile_30_png_size;
extern const Uint8* const CR_asset_tile_31_png;
extern const size_t CR_asset_tile_31_png_size;
extern const Uint8* const CR_asset_tile_32_png;
extern const size_t CR_asset_tile_32_png_size;
extern const Uint8* const CR_asset_tile_33_png;
extern const size_t CR_asset_tile_33_png_size;
extern const Uint8* const CR_asset_tile_34_png;
extern const size_t CR_asset_tile_34_png_size;
extern const Uint8* const CR_asset_tile_35_png;
extern const size_t CR_asset_tile_35_png_size;
extern const Uint8* const CR_asset_tile_36_png;
extern const size_t CR_asset_tile_36_png_size;
extern const Uint8* const CR_asset_tile_37_png;
extern const size_t CR_asset_tile_37_png_size;
extern const Uint8* const CR_asset_tile_38_png;
extern const size_t CR_asset_tile_38_png_size;
extern const Uint8* const CR_asset_tile_39_png;
extern const size_t CR_asset_tile_39_png_size;
extern const Uint8* const CR_asset_tile_40_png;
extern const size_t CR_asset_tile_40_png_size;
extern const Uint8* const CR_asset_tile_41_png;
extern const size_t CR_asset_tile_41_png_size;
extern const Uint8* const CR_asset_tile_42_png;
extern const size_t CR_asset_tile_42_png_size;
extern const Uint8* const CR_asset_tile_43_png;
extern const size_t CR_asset_tile_43_png_size;
extern const Uint8* const CR_asset_tile_44_png;
extern const size_t CR_asset_tile_44_png_size;
extern const Uint8* const CR_asset_tile_45_png;
extern const size_t CR_asset_tile_45_png_size;
extern const Uint8* const CR_asset_tile_46_png;
extern const size_t CR_asset_tile_46_png_size;
extern const Uint8* const CR_asset_tile_47_png;
extern const size_t CR_asset_tile_47_png_size;
extern const Uint8* const CR_asset_tile_48_png;
extern const size_t CR_asset_tile_48_png_size;
extern const Uint8* const CR_asset_tile_49_png;
extern const size_t CR_asset_tile_49_png_size;
extern const Uint8* const CR_asset_tile_50_png;
extern const size_t CR_asset_tile_50_png_size;
extern const Uint8* const CR_asset_tile_51_png;
extern const size_t CR_asset_tile_51_png_size;
extern const Uint8* const CR_asset_tile_52_png;
extern const size_t CR_asset_tile_52_png_size;
extern const Uint8* const CR_asset_tile_53_png;
extern const size_t CR_asset_tile_53_png_size;
extern const Uint8* const CR_asset_tile_54_png;
extern const size_t CR_asset_tile_54_png_size;
extern const Uint8* const CR_asset_tile_55_png;
extern const size_t CR_asset_tile_55_png_size;
extern const Uint8* const CR_asset_tile_56_png;
extern const size_t CR_asset_tile_56_png_size;
extern const Uint8* const CR_asset_tile_57_png;
extern const size_t CR_asset_tile_57_png_size;
extern const Uint8* const CR_asset_tile_58_png;
extern const size_t CR_asset_tile_58_png_size;
extern const Uint8* const CR_asset_tile_59_png;
extern const size_t CR_asset_tile_59_png_size;
extern const Uint8* const CR_asset_tile_60_png;
extern const size_t CR_asset_tile_60_png_size;
extern const Uint8* const CR_asset_tile_61_png;
extern const size_t CR_asset_tile_61_png_size;
extern const Uint8* const CR_asset_tile_62_png;
extern const size_t CR_asset_tile_62_png_size;
extern const Uint8* const CR_asset_tile_63_png;
extern const size_t CR_asset_tile_63_png_size;
extern const Uint8* const CR_asset_tile_64_png;
extern const size_t CR_asset_tile_64_png_size;
extern const Uint8* const CR_asset_tile_65_png;
extern const size_t CR_asset_tile_65_png_size;
extern const Uint8* const CR_asset_tile_66_png;
extern const size_t CR_asset_tile_66_png_size;
extern const Uint8* const CR_asset_tile_67_png;
extern const size_t CR_asset_tile_67_png_size;
extern const Uint8* const CR_asset_tile_68_png;
extern const size_t CR_asset_tile_68_png_size;
extern const Uint8* const CR_asset_tile_69_png;
extern const size_t CR_asset_tile_69_png_size;
extern const Uint8* const CR_asset_tile_70_png;
extern const size_t CR_asset_tile_70_png_size;
extern const Uint8* const CR_asset_tile_71_png;
extern const size_t CR_asset_tile_71_png_size;
extern const Uint8* const CR_asset_tile_72_png;
extern const size_t CR_asset_tile_72_png_size;
extern const Uint8* const CR_asset_tile_73_png;
extern const size_t CR_asset_tile_73_png_size;
extern const Uint8* const CR_asset_tile_74_png;
extern const size_t CR_asset_tile_74_png_size;
extern const Uint8* const CR_asset_tile_75_png;
extern const size_t CR_asset_tile_75_png_size;
extern const Uint8* const CR_asset_tile_76_png;
extern const size_t CR_asset_tile_76_png_size;
extern const Uint8* const CR_asset_tile_77_png;
extern const size_t CR_asset_tile_77_png_size;
extern const Uint8* const CR_asset_tile_78_png;
extern const size_t CR_asset_tile_78_png_size;
extern const Uint8* const CR_asset_tile_79_png;
extern const size_t CR_asset_tile_79_png_size;
extern const Uint8* const CR_asset_tile_80_png;
extern const size_t CR_asset_tile_80_png_size;
extern const Uint8* const CR_asset_tile_81_png;
extern const size_t CR_asset_tile_81_png_size;
extern const Uint8* const CR_asset_tile_82_png;
extern const size_t CR_asset_tile_82_png_size;
extern const Uint8* const CR_asset_tile_83_png;
extern const size_t CR_asset_tile_83_png_size;
extern const Uint8* const CR_asset_tile_84_png;
extern const size_t CR_asset_tile_84_png_size;
extern const Uint8* const CR_asset_tile_85_png;
extern const size_t CR_asset_tile_85_png_size;
extern const Uint8* const CR_asset_tile_86_png;
extern const size_t CR_asset_tile_86_png_size;
extern const Uint8* const CR_asset_tile_87_png;
extern const size_t CR_asset_tile_87_png_size;
extern const Uint8* const CR_asset_tile_88_png;
extern const size_t CR_asset_tile_88_png_size;
extern const Uint8* const CR_asset_tile_89_png;
extern const size_t CR_asset_tile_89_png_size;
extern const Uint8* const CR_asset_tile_90_png;
extern const size_t CR_asset_tile_90_png_size;
extern const Uint8* const CR_asset_tile_91_png;
extern const size_t CR_asset_tile_91_png_size;
extern const Uint8* const CR_asset_tile_92_png;
extern const size_t CR_asset_tile_92_png_size;
extern const Uint8* const CR_asset_tile_93_png;
extern const size_t CR_asset_tile_93_png_size;
extern const Uint8* const CR_asset_tile_94_png;
extern const size_t CR_asset_tile_94_png_size;
extern const Uint8* const CR_asset_tile_95_png;
extern const size_t CR_asset_tile_95_png_size;
extern const Uint8* const CR_asset_tile_96_png;
extern const size_t CR_asset_tile_96_png_size;
extern const Uint8* const CR_asset_tile_97_png;
extern const size_t CR_asset_tile_97_png_size;
extern const Uint8* const CR_asset_tile_98_png;
extern const size_t CR_asset_tile_98_png_size;
extern const Uint8* const CR_asset_tile_99_png;
extern const size_t CR_asset_tile_99_png_size;
extern const Uint8* const CR_asset_tile_100_png;
extern const size_t CR_asset_tile_100_png_size;
extern const Uint8* const CR_asset_tile_101_png;
extern const size_t CR_asset_tile_101_png_size;
extern const Uint8* const CR_asset_tile_102_png;
extern const size_t CR_asset_tile_102_png_size;
extern const Uint8* const CR_asset_tile_103_png;
extern const size_t CR_asset_tile_103_png_size;
extern const Uint8* const CR_asset_tile_104_png;
extern const size_t CR_asset_tile_104_png_size;
extern const Uint8* const CR_asset_tile_105_png;
extern const size_t CR_asset_tile_105_png_size;
extern const Uint8* const CR_asset_tile_106_png;
extern const size_t CR_asset_tile_106_png_size;
extern const Uint8* const CR_asset_tile_107_png;
extern const size_t CR_asset_tile_107_png_size;
extern const Uint8* const CR_asset_tile_108_png;
extern const size_t CR_asset_tile_108_png_size;
extern const Uint8* const CR_asset_tile_109_png;
extern const size_t CR_asset_tile_109_png_size;
extern const Uint8* const CR_asset_tile_110_png;
extern const size_t CR_asset_tile_110_png_size;
extern const Uint8* const CR_asset_tile_111_png;
extern const size_t CR_asset_tile_111_png_size;
extern const Uint8* const CR_asset_tile_112_png;
extern const size_t CR_asset_tile_112_png_size;
extern const Uint8* const CR_asset_tile_113_png;
extern const size_t CR_asset_tile_113_png_size;
extern const Uint8* const CR_asset_tile_114_png;
extern const size_t CR_asset_tile_114_png_size;
extern const Uint8* const CR_asset_tile_115_png;
extern const size_t CR_asset_tile_115_png_size;
extern const Uint8* const CR_asset_tile_116_png;
extern const size_t CR_asset_tile_116_png_size;
extern const Uint8* const CR_asset_tile_117_png;
extern const size_t CR_asset_tile_117_png_size;
extern const Uint8* const CR_asset_tile_118_png;
extern const size_t CR_asset_tile_118_png_size;
extern const Uint8* const CR_asset_tile_119_png;
extern const size_t CR_asset_tile_119_png_size;
extern const Uint8* const CR_asset_tile_120_png;
extern const size_t CR_asset_tile_120_png_size;
extern const Uint8* const CR_asset_tile_121_png;
extern const size_t CR_asset_tile_121_png_size;
extern const Uint8* const CR_asset_tile_122_png;
extern const size_t CR_asset_tile_122_png_size;
extern const Uint8* const CR_asset_tile_123_png;
extern const size_t CR_asset_tile_123_png_size;
extern const Uint8* const CR_asset_tile_124_png;
extern const size_t CR_asset_tile_124_png_size;
extern const Uint8* const CR_asset_tile_125_png;
extern const size_t CR_asset_tile_125_png_size;
extern const Uint8* const CR_asset_tile_126_png;
extern const size_t CR_asset_tile_126_png_size;

extern const Uint8* const CR_asset_player_idle_png;
extern const size_t CR_asset_player_idle_png_size;
extern const Uint8* const CR_asset_player_run_png;
extern const size_t CR_asset_player_run_png_size;

#endif /* __CR_ASSET_H__ */
