#if !defined __CR_ASSET_H__
#define __CR_ASSET_H__

#include "CR_common.h"

extern const char* const CR_asset_final_vert;
extern const char* const CR_asset_final_frag;

extern const char* const CR_asset_scene_vert;
extern const char* const CR_asset_scene_frag;

extern const Uint8* const CR_asset_default_png;
extern const size_t CR_asset_default_png_size;

extern const Uint8* const CR_asset_blank_png;
extern const size_t CR_asset_blank_png_size;

extern const Uint8* const CR_asset_background_1_png;
extern const size_t CR_asset_background_1_png_size;
extern const Uint8* const CR_asset_background_2_png;
extern const size_t CR_asset_background_2_png_size;
extern const Uint8* const CR_asset_background_3_png;
extern const size_t CR_asset_background_3_png_size;
extern const Uint8* const CR_asset_background_4_png;
extern const size_t CR_asset_background_4_png_size;
extern const Uint8* const CR_asset_background_5_png;
extern const size_t CR_asset_background_5_png_size;

extern const Uint8* const CR_asset_level_png;
extern const size_t CR_asset_level_png_size;

extern const Uint8* const CR_asset_tile_1_png;
extern const size_t CR_asset_tile_1_png_size;
extern const Uint8* const CR_asset_tile_2_png;
extern const size_t CR_asset_tile_2_png_size;
extern const Uint8* const CR_asset_tile_3_png;
extern const size_t CR_asset_tile_3_png_size;
extern const Uint8* const CR_asset_tile_4_png;
extern const size_t CR_asset_tile_4_png_size;
extern const Uint8* const CR_asset_tile_5_png;
extern const size_t CR_asset_tile_5_png_size;
extern const Uint8* const CR_asset_tile_6_png;
extern const size_t CR_asset_tile_6_png_size;
extern const Uint8* const CR_asset_tile_7_png;
extern const size_t CR_asset_tile_7_png_size;
extern const Uint8* const CR_asset_tile_8_png;
extern const size_t CR_asset_tile_8_png_size;
extern const Uint8* const CR_asset_tile_9_png;
extern const size_t CR_asset_tile_9_png_size;
extern const Uint8* const CR_asset_tile_10_png;
extern const size_t CR_asset_tile_10_png_size;
extern const Uint8* const CR_asset_tile_11_png;
extern const size_t CR_asset_tile_11_png_size;
extern const Uint8* const CR_asset_tile_12_png;
extern const size_t CR_asset_tile_12_png_size;
extern const Uint8* const CR_asset_tile_13_png;
extern const size_t CR_asset_tile_13_png_size;
extern const Uint8* const CR_asset_tile_14_png;
extern const size_t CR_asset_tile_14_png_size;
extern const Uint8* const CR_asset_tile_15_png;
extern const size_t CR_asset_tile_15_png_size;
extern const Uint8* const CR_asset_tile_16_png;
extern const size_t CR_asset_tile_16_png_size;
extern const Uint8* const CR_asset_tile_17_png;
extern const size_t CR_asset_tile_17_png_size;
extern const Uint8* const CR_asset_tile_18_png;
extern const size_t CR_asset_tile_18_png_size;
extern const Uint8* const CR_asset_tile_19_png;
extern const size_t CR_asset_tile_19_png_size;
extern const Uint8* const CR_asset_tile_20_png;
extern const size_t CR_asset_tile_20_png_size;
extern const Uint8* const CR_asset_tile_21_png;
extern const size_t CR_asset_tile_21_png_size;
extern const Uint8* const CR_asset_tile_22_png;
extern const size_t CR_asset_tile_22_png_size;
extern const Uint8* const CR_asset_tile_23_png;
extern const size_t CR_asset_tile_23_png_size;
extern const Uint8* const CR_asset_tile_24_png;
extern const size_t CR_asset_tile_24_png_size;
extern const Uint8* const CR_asset_tile_25_png;
extern const size_t CR_asset_tile_25_png_size;
extern const Uint8* const CR_asset_tile_26_png;
extern const size_t CR_asset_tile_26_png_size;
extern const Uint8* const CR_asset_tile_27_png;
extern const size_t CR_asset_tile_27_png_size;
extern const Uint8* const CR_asset_tile_28_png;
extern const size_t CR_asset_tile_28_png_size;
extern const Uint8* const CR_asset_tile_29_png;
extern const size_t CR_asset_tile_29_png_size;
extern const Uint8* const CR_asset_tile_30_png;
extern const size_t CR_asset_tile_30_png_size;
extern const Uint8* const CR_asset_tile_31_png;
extern const size_t CR_asset_tile_31_png_size;
extern const Uint8* const CR_asset_tile_32_png;
extern const size_t CR_asset_tile_32_png_size;
extern const Uint8* const CR_asset_tile_33_png;
extern const size_t CR_asset_tile_33_png_size;
extern const Uint8* const CR_asset_tile_34_png;
extern const size_t CR_asset_tile_34_png_size;
extern const Uint8* const CR_asset_tile_35_png;
extern const size_t CR_asset_tile_35_png_size;
extern const Uint8* const CR_asset_tile_36_png;
extern const size_t CR_asset_tile_36_png_size;
extern const Uint8* const CR_asset_tile_37_png;
extern const size_t CR_asset_tile_37_png_size;
extern const Uint8* const CR_asset_tile_38_png;
extern const size_t CR_asset_tile_38_png_size;
extern const Uint8* const CR_asset_tile_39_png;
extern const size_t CR_asset_tile_39_png_size;
extern const Uint8* const CR_asset_tile_40_png;
extern const size_t CR_asset_tile_40_png_size;
extern const Uint8* const CR_asset_tile_41_png;
extern const size_t CR_asset_tile_41_png_size;
extern const Uint8* const CR_asset_tile_42_png;
extern const size_t CR_asset_tile_42_png_size;
extern const Uint8* const CR_asset_tile_43_png;
extern const size_t CR_asset_tile_43_png_size;
extern const Uint8* const CR_asset_tile_44_png;
extern const size_t CR_asset_tile_44_png_size;
extern const Uint8* const CR_asset_tile_45_png;
extern const size_t CR_asset_tile_45_png_size;
extern const Uint8* const CR_asset_tile_46_png;
extern const size_t CR_asset_tile_46_png_size;
extern const Uint8* const CR_asset_tile_47_png;
extern const size_t CR_asset_tile_47_png_size;
extern const Uint8* const CR_asset_tile_48_png;
extern const size_t CR_asset_tile_48_png_size;
extern const Uint8* const CR_asset_tile_49_png;
extern const size_t CR_asset_tile_49_png_size;
extern const Uint8* const CR_asset_tile_50_png;
extern const size_t CR_asset_tile_50_png_size;
extern const Uint8* const CR_asset_tile_51_png;
extern const size_t CR_asset_tile_51_png_size;
extern const Uint8* const CR_asset_tile_52_png;
extern const size_t CR_asset_tile_52_png_size;
extern const Uint8* const CR_asset_tile_53_png;
extern const size_t CR_asset_tile_53_png_size;
extern const Uint8* const CR_asset_tile_54_png;
extern const size_t CR_asset_tile_54_png_size;
extern const Uint8* const CR_asset_tile_55_png;
extern const size_t CR_asset_tile_55_png_size;
extern const Uint8* const CR_asset_tile_56_png;
extern const size_t CR_asset_tile_56_png_size;
extern const Uint8* const CR_asset_tile_57_png;
extern const size_t CR_asset_tile_57_png_size;
extern const Uint8* const CR_asset_tile_58_png;
extern const size_t CR_asset_tile_58_png_size;
extern const Uint8* const CR_asset_tile_59_png;
extern const size_t CR_asset_tile_59_png_size;
extern const Uint8* const CR_asset_tile_60_png;
extern const size_t CR_asset_tile_60_png_size;
extern const Uint8* const CR_asset_tile_61_png;
extern const size_t CR_asset_tile_61_png_size;
extern const Uint8* const CR_asset_tile_62_png;
extern const size_t CR_asset_tile_62_png_size;
extern const Uint8* const CR_asset_tile_63_png;
extern const size_t CR_asset_tile_63_png_size;
extern const Uint8* const CR_asset_tile_64_png;
extern const size_t CR_asset_tile_64_png_size;
extern const Uint8* const CR_asset_tile_65_png;
extern const size_t CR_asset_tile_65_png_size;
extern const Uint8* const CR_asset_tile_66_png;
extern const size_t CR_asset_tile_66_png_size;
extern const Uint8* const CR_asset_tile_67_png;
extern const size_t CR_asset_tile_67_png_size;
extern const Uint8* const CR_asset_tile_68_png;
extern const size_t CR_asset_tile_68_png_size;
extern const Uint8* const CR_asset_tile_69_png;
extern const size_t CR_asset_tile_69_png_size;
extern const Uint8* const CR_asset_tile_70_png;
extern const size_t CR_asset_tile_70_png_size;

extern const Uint8* const CR_asset_player_idle_png;
extern const size_t CR_asset_player_idle_png_size;
extern const Uint8* const CR_asset_player_run_png;
extern const size_t CR_asset_player_run_png_size;

#endif /* __CR_ASSET_H__ */
